
#wheel_width: The width of the wheels
#wheel_radius: The radius of the wheels
#wheel_base: The distance between the centers wheels
#chassis_length: The length of the main chassis link
#chassis_thickness: The thickness of the plate that forms the chassis
#wheel_axle_offset: distance between a wheel axle and the bottom of the chassis

wheel_width: 0.018
wheel_radius: 0.033
wheel_base: 0.16
chassis_length: 0.138
chassis_thickness: 0.140
wheel_mass: 0.03
chassis_mass: 1.0
wheel_axle_offset: 0.02
laser_scanner_radius: 0.02
laser_scanner_height: 0.02



