// Generated by gencpp from file tsim/traj_reset.msg
// DO NOT EDIT!


#ifndef TSIM_MESSAGE_TRAJ_RESET_H
#define TSIM_MESSAGE_TRAJ_RESET_H

#include <ros/service_traits.h>


#include <tsim/traj_resetRequest.h>
#include <tsim/traj_resetResponse.h>


namespace tsim
{

struct traj_reset
{

typedef traj_resetRequest Request;
typedef traj_resetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct traj_reset
} // namespace tsim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tsim::traj_reset > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::tsim::traj_reset&) { return value(); }
};

template<>
struct DataType< ::tsim::traj_reset > {
  static const char* value()
  {
    return "tsim/traj_reset";
  }

  static const char* value(const ::tsim::traj_reset&) { return value(); }
};


// service_traits::MD5Sum< ::tsim::traj_resetRequest> should match 
// service_traits::MD5Sum< ::tsim::traj_reset > 
template<>
struct MD5Sum< ::tsim::traj_resetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tsim::traj_reset >::value();
  }
  static const char* value(const ::tsim::traj_resetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tsim::traj_resetRequest> should match 
// service_traits::DataType< ::tsim::traj_reset > 
template<>
struct DataType< ::tsim::traj_resetRequest>
{
  static const char* value()
  {
    return DataType< ::tsim::traj_reset >::value();
  }
  static const char* value(const ::tsim::traj_resetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tsim::traj_resetResponse> should match 
// service_traits::MD5Sum< ::tsim::traj_reset > 
template<>
struct MD5Sum< ::tsim::traj_resetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tsim::traj_reset >::value();
  }
  static const char* value(const ::tsim::traj_resetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tsim::traj_resetResponse> should match 
// service_traits::DataType< ::tsim::traj_reset > 
template<>
struct DataType< ::tsim::traj_resetResponse>
{
  static const char* value()
  {
    return DataType< ::tsim::traj_reset >::value();
  }
  static const char* value(const ::tsim::traj_resetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TSIM_MESSAGE_TRAJ_RESET_H
